CREATE TABLE departments
(
    id                int8 generated by default as identity,
    name              varchar(255) not null,
    description       varchar(255) not null,
    phone_number      varchar(255) not null,
    date_of_formation timestamp    not null,

    primary key (id)
);

CREATE TABLE employees
(
    id                 int8 generated by default as identity,
    full_name          varchar(255),
    date_of_birth      timestamp    not null,
    phone_number       varchar(255) not null,
    email_address      varchar(255) not null,
    position           varchar(30)  not null,
    date_of_employment timestamp    not null,
    department_id      int8 default null,

    primary key (id),
    foreign key (department_id) references departments (id)
);

-- INSERT DEPARTMENTS
insert into departments (name, description, phone_number, date_of_formation)
values ('Logistics Department', 'logistics, expedition, planning', '+375336446244', '2008-03-15');
insert into departments (name, description, phone_number, date_of_formation)
values ('Transport Service', 'tire fitting, car wash, drivers', '+375336333140', '2020-09-01');


-- INSERT EMPLOYEES
insert into employees (full_name, date_of_birth, phone_number, email_address, position, date_of_employment, department_id)
values ('Sergey Ignatuk', '1989-08-07', '+375295326531', 's.ignatyuk@yuridan.by', 'scheduler', '2012-11-14', 1);

insert into employees (full_name, date_of_birth, phone_number, email_address, position, date_of_employment, department_id)
values ('Natasha Ignatuk', '1989-04-04', '+375336718108', 'info@yuridan.by', 'forwarder', '2013-09-20', 1);

insert into employees (full_name, date_of_birth, phone_number, email_address, position, date_of_employment)
values ('Ivanovskaya Yulia', '1988-07-31', '+375295202152', 'info@yuridan.by', 'forwarder', '2014-10-31');

